# Generated by Django 6.0.3 on 2026-03-22 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seat', '0003_alter_seat_unique_together_seatreservation'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='seat.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
