# Generated by Django 6.0.3 on 2026-03-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row', models.CharField(max_length=2)),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('hold', 'Hold'), ('purchased', 'Purchased')], default='available', max_length=20)),
            ],
            options={
                'ordering': ['row', 'number'],
                'unique_together': {('row', 'number')},
            },
        ),
    ]
