# Generated by Django 6.0.3 on 2026-03-22 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0003_alter_seat_unique_together_seatreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatreservation',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='seat.seat'),
        ),
    ]
